added Alternative reach access
ori-community/wotw-rando-client pull request #347
Opened 2024-02-01 23:46 UTC by LoadCake

Added support for making baur sneeze with blaze and flash

2024-02-02 00:21 UTC, timoschwarzer requested changes

2024-02-02 00:21 UTC, timoschwarzer commented on projects/Randomizer/game/behaviour_changes/alternative_baurs_reach_access.cpp
> +        if(should_open_condition) {
space

2024-02-02 00:21 UTC, timoschwarzer commented on projects/Randomizer/game/behaviour_changes/alternative_baurs_reach_access.cpp
> +    bool should_open_condition;
this does not need to be in global scope

2024-02-02 00:21 UTC, timoschwarzer commented on projects/Randomizer/game/behaviour_changes/alternative_baurs_reach_access.cpp
> +                    if(restrict_zone->is_valid()) {
space

2024-02-02 00:21 UTC, timoschwarzer commented on projects/Randomizer/game/behaviour_changes/alternative_baurs_reach_access.cpp
> +                        (**restrict_zone)->fields.RestrictMask = static_cast<app::SeinAbilityRestrictZoneMask__Enum>(mask);
indentation

2024-02-02 19:39 UTC, timoschwarzer requested changes

2024-02-02 19:39 UTC, timoschwarzer commented on projects/Randomizer/game/behaviour_changes/alternative_baurs_reach_access.cpp
> +        }
```suggestion
        const auto should_open =
            ability_should_open.contains(result.Damage->fields.m_abilityType) &&
            ability_should_open.at(result.Damage->fields.m_abilityType).get<bool>();
        
        if (should_open) {
            result.Damage->fields.m_damageType = app::DamageType__Enum::Wind;
        }
```

2024-02-02 19:39 UTC, timoschwarzer commented on projects/Randomizer/game/behaviour_changes/alternative_baurs_reach_access.cpp
> +                        }
handling for Flash is missing

2024-02-02 19:39 UTC, timoschwarzer commented on projects/Randomizer/uber_states/uber_state_initialization.cpp
> +                add_state<app::SerializedBooleanUberState>(UberStateGroup::RandoState, "BaurSneezeWithFlash", 421, false),
B → b and move to RandoConfig

2024-02-02 22:47 UTC, LoadCake commented on projects/Randomizer/game/behaviour_changes/alternative_baurs_reach_access.cpp
> +                        }
Flash does not get locked by the Damage mask. Even with the original restrict zone it was possible to use flash

2024-02-05 13:30 UTC, timoschwarzer approved these changes

2024-02-05 13:30 UTC, merged