Archipelago client (WIP)
ori-community/wotw-rando-client pull request #357
Opened 2024-12-30 20:51 UTC by Satisha10

Additions:
- Handle most of the packets (e.g. items received, items sent, data packages, messages).
- Detects when a location is checked, and when the game is finished.

TODO:
- Testing and debug.
- Parse the seed file and get the connection informations.

2024-12-30 22:01 UTC, timoschwarzer commented on projects/Randomizer/archipelago/archipelago.cpp
> +                    send_message(messages::StatusUpdate{30});
Where does the 30 come from? :eyes:

2024-12-30 22:10 UTC, timoschwarzer commented on projects/Randomizer/archipelago/archipelago.h
> +        core::api::uber_states::UberState(15, 41666)
Can we generate this at runtime from loc_data.csv instead of hardcoding it here?

2024-12-30 22:13 UTC, timoschwarzer commented on projects/Randomizer/archipelago/archipelago.cpp
> +        m_location_id_to_name = read_file("ap_location_id_to_name.json");
Is this supposed to be reading the same file?

2024-12-31 10:20 UTC, timoschwarzer commented on projects/Randomizer/archipelago/archipelago.cpp
> +                        collected->value.set(item.value);
```suggestion
                        const auto spirit_light = core::api::game::player::spirit_light();
                        const auto spirit_light_collected = core::api::uber_states::UberState(UberStateGroup::RandoStats, 3);
                        
                        spirit_light.set(spirit_light.get() + 1);
                        spirit_light_collected.set<int>(spirit_light_collected.get<int>() + 1);
```

2024-12-31 10:22 UTC, timoschwarzer commented on projects/Randomizer/archipelago/archipelago.cpp
> +#include "Core/api/uber_states/uber_state.h"
```suggestion
#include <Core/api/uber_states/uber_state.h>
```

everywhere 🙂

2024-12-31 10:27 UTC, timoschwarzer commented on projects/Randomizer/archipelago/archipelago.cpp
> +    }
For reading files, we already have `read_text_file(...)` in `ext.h`. For paths, `std::filesystem::path` should be used instead of `std::string`.

2024-12-31 10:31 UTC, timoschwarzer commented on projects/Randomizer/archipelago/archipelago.cpp
> +    }
...we also have `load_json_file(...)` that takes a file name directly and handles prepending the base path and handling errors.

```cpp
nlohmann::json j;
if (!load_json_file("something.json", j)) {
  // Something went wrong
  // Error message is printed to modloader log
  return;
}
```

2024-12-31 10:31 UTC, timoschwarzer commented on projects/Randomizer/archipelago/archipelago_protocol.cpp
> +        return message.get<LocationInfo>();
```suggestion
            return message.get<LocationInfo>();
```

💨

2024-12-31 10:37 UTC, timoschwarzer commented on projects/Randomizer/archipelago/archipelago.cpp
> +    }
Use `std::filesystem::path` and prepend `base_path()`.

2024-12-31 10:40 UTC, timoschwarzer requested changes
Added some comments and TODOs here and there. 🙂

One thing that I noticed is that you never check against the `received_items` vector - you only push received items into it. I don't remember how this was supposed to be done right now, so this is just a reminder to remember this.

2024-12-31 12:49 UTC, MunWolf commented on projects/Randomizer/archipelago/archipelago.cpp
> +            }
Should run clang-format on the files so the codestyle is correct

2024-12-31 12:50 UTC, MunWolf commented on projects/Randomizer/archipelago/archipelago.cpp
> +            return m_location_id_to_name[game][id];
better to use m_location_id_to_name.find() here, then you aren't searching through it twice.

2024-12-31 13:02 UTC, MunWolf commented on projects/Randomizer/archipelago/archipelago_protocol.h
> +    // Data structures
Unnecessary comment

2024-12-31 13:09 UTC, MunWolf commented on projects/Randomizer/archipelago/archipelago.cpp
> +                        refill->type = randomizer::seed::items::Refill::RefillType::Health;
Unless I am missing something you are making these and then not doing anything with them?
Feel like there is a misunderstanding how the items work.

2024-12-31 13:14 UTC, MunWolf commented
If I remember correctly the plan was to map archipelago location ids to uberstates and map our own locations to archipelago location ids.
And then just have a normal seed file take care of translating those into items (in which case you shouldn't need to work with randomizer::seed:items at all)
Might be wrong though, been a very long time since I was last involved in rando discussions, not to mention archipelago

2024-12-31 14:21 UTC, Satisha10 commented on projects/Randomizer/archipelago/archipelago.cpp
> +                    send_message(messages::StatusUpdate{30});
It is the value used by AP to indicate that the goal is completed (cf `ClientStatus` in the network protocol doc).

2024-12-31 16:10 UTC, Satisha10 commented on projects/Randomizer/archipelago/archipelago.h
> +        core::api::uber_states::UberState(15, 41666)
It should be possible, I will look at that later.

2024-12-31 16:10 UTC, Satisha10 commented on projects/Randomizer/archipelago/archipelago.cpp
> +        m_location_id_to_name = read_file("ap_location_id_to_name.json");
That was a typo, fixed.

2024-12-31 16:12 UTC, Satisha10 commented on projects/Randomizer/archipelago/archipelago.cpp
> +                        collected->value.set(item.value);
Thank you ! I copied some code from `legacy_parser/parser.cpp` but misunderstood it. I also fixed the other resources.

2024-12-31 16:13 UTC, Satisha10 commented on projects/Randomizer/archipelago/archipelago.cpp
> +#include "Core/api/uber_states/uber_state.h"
Should be fixed (if I did not miss one of them).

2024-12-31 16:14 UTC, Satisha10 commented on projects/Randomizer/archipelago/archipelago.cpp
> +    }
Thanks, I changed it to use `load_json_file`.

2024-12-31 16:15 UTC, Satisha10 commented on projects/Randomizer/archipelago/archipelago_protocol.cpp
> +        return message.get<LocationInfo>();
Fixed.

2024-12-31 16:15 UTC, Satisha10 commented on projects/Randomizer/archipelago/archipelago.cpp
> +    }
Changed it.

2024-12-31 16:17 UTC, Satisha10 commented on projects/Randomizer/archipelago/archipelago_protocol.h
> +    // Data structures
I removed it.

2024-12-31 16:20 UTC, Satisha10 commented on projects/Randomizer/archipelago/archipelago.cpp
> +                        refill->type = randomizer::seed::items::Refill::RefillType::Health;
I copied some code from `legacy_parser/parser.cpp` without fully understanding it. I hopefully fixed that for all resources based on zre's suggestion.

2024-12-31 16:28 UTC, Satisha10 commented
> If I remember correctly the plan was to map archipelago location ids to uberstates and map our own locations to archipelago location ids. And then just have a normal seed file take care of translating those into items (in which case you shouldn't need to work with randomizer::seed:items at all) Might be wrong though, been a very long time since I was last involved in rando discussions, not to mention archipelago

The seed file only contains headers to setup the game file according to the options (to include `seed_core`, and for things like random spawn, no quests, goal mode, QOL). It does not contain any information about which item is in each pickup, this info is sent by the AP server after a pickup is collected (with a `LocationInfo` packet).

2025-01-01 11:27 UTC, Satisha10 commented on projects/Randomizer/archipelago/archipelago.cpp
> +                    send_message(messages::StatusUpdate{30});
I added an enum structure in `archipelago_protocol.h` for the client status to make it more clear.

2025-01-01 11:29 UTC, Satisha10 commented on projects/Randomizer/archipelago/archipelago.h
> +        core::api::uber_states::UberState(15, 41666)
It is now built in `archipelago.cpp` (I adapted your code from `archipelago_ids.cpp` for that).

2025-01-01 11:31 UTC, Satisha10 commented on projects/Randomizer/archipelago/archipelago.cpp
> +            return m_location_id_to_name[game][id];
Thanks, I changed it in other places too.

2025-01-01 15:20 UTC, Satisha10 commented on projects/Randomizer/archipelago/archipelago.cpp
> +            }
Thanks, I applied it to all the files.

2025-01-01 15:35 UTC, Satisha10 commented
> One thing that I noticed is that you never check against the `received_items` vector - you only push received items into it. I don't remember how this was supposed to be done right now, so this is just a reminder to remember this.
I think that storing the items is not needed at all, since the only thing used to check for desyncs is the last item index (which increases by 1 for each received item), so I removed `received_items` and added the `last_item_index` in `archipelago_save_meta.cpp`.

2025-01-31 12:38 UTC, timoschwarzer commented on projects/Randomizer/archipelago/archipelago_protocol.h
> +        std::string original_cmd;  // TODO can be null, which causes the parsing to fail
I *think* you can use `std::optional<std::string>` then to allow `null` values.

2025-02-02 15:01 UTC, Satisha10 commented on projects/Randomizer/archipelago/archipelago_protocol.h
> +        std::string original_cmd;  // TODO can be null, which causes the parsing to fail
Apparently the `NLOHMANN_DEFINE_TYPE_INTRUSIVE` macro does not support conversion of optional, so I don't think it is an easy fix. I will just leave it like that for now since it is only a debug packet, and the full packet is still written `modloader_log` if the parsing fails.

2025-04-29 20:29 UTC, timoschwarzer commented
Will close this as it is merged by now. Thank you again!!

2025-04-29 20:29 UTC, closed without merging